# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Game.Model.finger_game import FingerGameUI

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.close = QtWidgets.QPushButton(self.centralwidget)
        self.close.setGeometry(QtCore.QRect(50, 320, 81, 26))
        self.close.setObjectName("close")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(190, 80, 551, 401))
        self.graphicsView.setObjectName("graphicsView")
        self.finger_game = QtWidgets.QPushButton(self.centralwidget)
        self.finger_game.setGeometry(QtCore.QRect(50, 180, 81, 26))
        self.finger_game.setObjectName("finger_game")
        self.situp_game = QtWidgets.QPushButton(self.centralwidget)
        self.situp_game.setGeometry(QtCore.QRect(50, 250, 81, 26))
        self.situp_game.setObjectName("situp_game")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.close.setText(_translate("MainWindow", "退出程序"))
        self.finger_game.setText(_translate("MainWindow", "手指乒乓"))
        self.situp_game.setText(_translate("MainWindow", "仰卧起坐"))
