# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import cv2
# from Game.Model.finger_game import FingerGameUI
from Game.Model.pingpo import finger_game
class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.timer_camera = QtCore.QTimer()  # 定义定时器，用于控制显示视频的帧率
        self.cap = cv2.VideoCapture()  # 视频流
        self.CAM_NUM = 1  # 为0时表示视频流来自笔记本内置摄像头
        self.slot_init()  # 初始化槽函数

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        self.label_show_camera = QtWidgets.QLabel(self.centralwidget)
        self.label_show_camera.setGeometry(QtCore.QRect(150, 20, 1281, 721))
        self.label_show_camera.setObjectName("labelView")

        self.finger_game = QtWidgets.QPushButton(self.centralwidget)
        self.finger_game.setGeometry(QtCore.QRect(30, 180, 81, 26))
        self.finger_game.setObjectName("finger_game")

        self.situp_game = QtWidgets.QPushButton(self.centralwidget)
        self.situp_game.setGeometry(QtCore.QRect(30, 250, 81, 26))
        self.situp_game.setObjectName("situp_game")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.finger_game.setText(_translate("MainWindow", "手指乒乓"))
        self.situp_game.setText(_translate("MainWindow", "仰卧起坐"))

    def slot_init(self):
        '''初始化槽函数'''
        self.finger_game.clicked.connect(finger_game)
        # self.timer_camera.timeout.connect(self.show_camera)

    def button_fingergame_function(self):
        '''手指乒乓游戏'''
        # self.label_show_camera=FingerGameUI(self.label_show_camera)